# Generated by Django 2.2.3 on 2019-08-08 03:10

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0010_feed_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='tags',
        ),
        migrations.AlterField(
            model_name='feed',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='feed_photos'),
        ),
    ]
