# Generated by Django 2.2.3 on 2019-08-06 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0005_feed_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cloudy_posts',
            field=models.ManyToManyField(blank=True, related_name='cloudy_user', to='feedpage.Feed'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.TextField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='rainy_posts',
            field=models.ManyToManyField(blank=True, related_name='rainy_user', to='feedpage.Feed'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sunny_posts',
            field=models.ManyToManyField(blank=True, related_name='sunny_user', to='feedpage.Feed'),
        ),
    ]
