# Generated by Django 2.2.3 on 2019-08-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0007_auto_20190806_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='cloudy_content',
            field=models.TextField(default='흐림'),
        ),
        migrations.AddField(
            model_name='feed',
            name='rainy_content',
            field=models.TextField(default='비'),
        ),
        migrations.AddField(
            model_name='feed',
            name='sunny_content',
            field=models.TextField(default='맑음'),
        ),
    ]
