# Generated by Django 2.2.3 on 2019-08-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0016_auto_20190811_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
