# Generated by Django 2.2.3 on 2019-08-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0018_feed_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
