# Generated by Django 2.2.3 on 2019-08-11 08:04

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0019_auto_20190811_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=imagekit.models.fields.ProcessedImageField(default=1, upload_to='profile_photos'),
            preserve_default=False,
        ),
    ]
