# Generated by Django 2.2.3 on 2019-08-11 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0021_commentlike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
