# Generated by Django 2.2.3 on 2019-08-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0022_delete_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='nickname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
