# Generated by Django 2.2.3 on 2019-08-12 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0023_feed_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='hashtags',
            field=models.TextField(blank=True),
        ),
    ]
