# Generated by Django 2.2.3 on 2019-08-13 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0027_auto_20190813_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdislike',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedpage.Feed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentlike',
            name='feed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedpage.Feed'),
            preserve_default=False,
        ),
    ]
