# Generated by Django 2.2.3 on 2019-08-13 04:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedpage', '0028_auto_20190813_1312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentLike',
            new_name='Dislike',
        ),
        migrations.RenameModel(
            old_name='CommentDislike',
            new_name='Like',
        ),
    ]
