# Generated by Django 2.2.3 on 2019-08-13 05:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0029_auto_20190813_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedcomment',
            name='disliked_users',
            field=models.ManyToManyField(blank=True, related_name='comments_disliked', through='feedpage.Dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedcomment',
            name='liked_users',
            field=models.ManyToManyField(blank=True, related_name='comments_liked', through='feedpage.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
