# Generated by Django 2.2.3 on 2019-08-13 05:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedpage', '0030_auto_20190813_1401'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dislike',
            new_name='CommentDislike',
        ),
        migrations.RenameModel(
            old_name='Like',
            new_name='CommentLike',
        ),
    ]
