# Generated by Django 2.2.3 on 2019-08-13 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0031_auto_20190813_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='status',
            new_name='lovestatus',
        ),
    ]
