# Generated by Django 2.2.3 on 2019-08-14 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0035_auto_20190814_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
