# Generated by Django 2.2.3 on 2019-08-14 02:16

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0036_auto_20190814_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='feed_photos')),
            ],
        ),
        migrations.AddField(
            model_name='feed',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedpage.Photos'),
        ),
    ]
