# Generated by Django 2.2.3 on 2019-08-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0037_auto_20190814_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='photo',
        ),
        migrations.AddField(
            model_name='feed',
            name='photo',
            field=models.ManyToManyField(null=True, to='feedpage.Photos'),
        ),
    ]
