# Generated by Django 2.2.3 on 2019-08-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0041_auto_20190814_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='photo',
        ),
        migrations.AddField(
            model_name='feed',
            name='photo',
            field=models.ManyToManyField(to='feedpage.Photos'),
        ),
    ]
