# Generated by Django 2.2.3 on 2019-08-14 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0042_auto_20190815_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='photo',
        ),
        migrations.AddField(
            model_name='feed',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feedpage.Photos'),
        ),
    ]
