# Generated by Django 2.2.3 on 2019-08-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0044_auto_20190815_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.FileField(upload_to='feed_photos'),
        ),
    ]
