# Generated by Django 2.2.3 on 2019-08-14 16:36

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0045_auto_20190815_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(upload_to='feed_photos'),
        ),
    ]
