# Generated by Django 2.2.3 on 2019-08-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0046_auto_20190815_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
