# Generated by Django 2.2.3 on 2019-08-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0049_feed_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='result',
            field=models.CharField(default='not confirmed', max_length=200),
        ),
    ]
