# Generated by Django 2.2.3 on 2019-08-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0051_auto_20190817_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_photos',
            field=models.ManyToManyField(related_name='feed_photo', to='feedpage.Photos'),
        ),
    ]
