# Generated by Django 2.2.3 on 2019-08-17 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0054_auto_20190817_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedpage.Notification'),
            preserve_default=False,
        ),
    ]
