# Generated by Django 2.2.3 on 2019-08-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0055_profile_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notifications',
        ),
    ]
